version: '3'
services:
  fluent-bit:
    container_name: fluent-bit
    image: fluent/fluent-bit
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./test.log:/var/log/test.log
    networks:
      - opensearch-net
  
  data-prepper:
    container_name: data-prepper
    image: opensearchproject/data-prepper:2
    volumes:
      - ./log-pipeline.yaml:/usr/share/data-prepper/pipelines/log_pipeline.yaml
    ports:
      - 2021:2021
    networks:
      - opensearch-net

  opensearch:
    container_name: opensearch
    image: opensearchproject/opensearch:latest
    volumes:
      - ./opensearch.yaml:/usr/share/opensearch/config/opensearch.yml
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net
  
  dashboards:
    container_name: opensearch-dashboards
    image: opensearchproject/opensearch-dashboards:latest
    volumes:
      - ./opensearch-dashboards.yaml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
    ports:
      - 5601:5601
    expose:
      - "5601"
    depends_on:
      - opensearch
    networks:
      - opensearch-net

networks:
  opensearch-net:

